### ISSUE TITLE
Bug with Worldquest tracker add-on

### ISSUE THREAD

**Issue by Thomas1362** [liquidbase/DuffedUIv8#43] opened 2016-09-05 14:36 UTC
Message: ...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:4165: attempt to index local 'relativeTo' (a nil value)
Time: 09/05/16 16:32:33
Count: 1
Stack: ...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:4165: in function `RefreshAnchor'
...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:4717: in function `RefreshTrackerWidgets'
...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:4839: in function `UpdateQuestsInArea'
...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:4891: in function <...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:4884>
...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:4916: in function <...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:4915>
[C]: in function `ObjectiveTracker_Update'
...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:749: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:661>

Locals: (for index) = 1
(for limit) = 1
(for step) = 1
i = 1
point = "RIGHT"
relativeTo = nil
relativePoint = "RIGHT"
xOfs = -216
yOfs = 8
(*temporary) = "RIGHT"
(*temporary) = nil
(*temporary) = 8
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'relativeTo' (a nil value)"
WorldQuestTracker = <table> {
 LastUpdate = 0
 QUEST_COMMENTS = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\HandyNotes_LegionRaresTreasures\libs\AceTimer-3.0\AceTimer-3.0.lua:145
 GetQuest_Info = <function> defined @Interface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:1266
 UnregisterComm = <function> defined @Interface\AddOns\DuffedUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 Cache_ShownQuestOnWorldMap = <table> {
 }
 CheckTimeLeftOnQuestsFromTracker_Load = <function> defined @Interface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:4009
 QueuedRefresh = 1
 IconPick = <function> defined @Interface\AddOns\WorldQuestTracker\libs\DF\panel.lua:1094
 GetTemplate = <function> defined @Interface\AddOns\WorldQuestTracker\libs\DF\fw.lua:1005
 mapTables = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AddOnSkins\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 SetBountyAmountCompleted = <function> defined @Interface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:6421
 PlayLoadingAnimation = <function> defined @Interface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:6403
 GetAllWorldQuests_Ids = <function> defined @Interface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:886
 MapOpenedAt = 0
 ScheduleTimer = <function> defined @Interface\AddOns\HandyNotes_LegionRaresTreasures\libs\AceTimer-3.0\AceTimer-3.0.lua:92
 ShowPromptPanel = <function> defined @Interface\AddOns\WorldQuestTracker\libs\DF\panel.lua:1783
 RegisterMessage = <function> defined @Interface\AddOns\DuffedUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 Msg = <function> defined @Interface\AddOns\WorldQuestTracker\libs\DF\fw.lua:287
 CreateScrollBar = <function> defined @Interface\AddOns\WorldQuestTracker\libs\DF\scrollbar.lua:7
 ShowPanicWarning = <function> defined @Interface\AddOns\WorldQuestTracker\libs\DF\panel.lua:1436
 ShowTextPromptPanel = <function> defined @Interface\AddOns\WorldQuestTracker\libs\DF\panel.lua:1843
 db = <table> {
 }
 UnregisterAllComm = <function> defined @Interface\AddOns\DuffedUI\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 SetEnabledState = <function> defined @Interface\AddOns\AddOnSkins\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 ShowTutorialAlertFrame = <function> defined @Interface\AddOns\WorldQuestTracker\libs\DF\fw.lua:727
 QuestTrackList = <table> {
 }
 RefreshStatusBar = <function> defined @Interface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:1428
 HideZoneWidgets = <function> defined @Interface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:1776
 LastWorldMapClick = 0
 OnInit = <function> defined @Interface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:431
 GetQuestRewar

**Comment by Thomas1362** [comment] 2016-09-05 15:29
Hey , got this error today, is there a way to fix this ? :)

**Comment by Rav99** [comment] 2016-09-07 04:08
Sure, the error is related to WorldQuestTracker. Pls load a new version of WorldQuestTracker.

**Comment by liquidbase** [comment] 2016-09-07 14:26
As Rav said the issue is related to WorldQuestTracker. I had informed the
author with a potential fix and he implemented the fix. Load the new
version r63 from wowimterface or curse.

**Comment by liquidbase** [comment] 2016-09-08 13:47
Closing the issue.

**Closed by liquidbase** 2016-09-08 13:47 UTC
